spring:
  datasource:
    url: jdbc:mysql://localhost/bd_inventario
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true